from __future__ import annotations

from clonway_cockpit.mail import badge, breadcrumb, section_eyebrow, status_strip, wrap


def test_breadcrumb_names_worker_product_and_date() -> None:
    assert breadcrumb("xbook", "Daily digest", "2026-06-12") == (
        "Generated by xbook · Daily digest · 2026-06-12"
    )


def test_wrap_is_a_full_document_with_header_and_footer_breadcrumb() -> None:
    html = wrap(
        "<div>BODY-MARKER</div>",
        eyebrow="xbook · Payroll & Invoicing chat",
        tenant="Clonway Care Limited",
        subtitle="Thursday 11 June 2026",
        worker="xbook",
        product="Payroll & Invoicing chat",
        date="2026-06-11",
    )

    assert html.startswith("<!DOCTYPE html>")
    assert html.rstrip().endswith("</html>")
    # header band carries the eyebrow + tenant
    assert "Clonway Care Limited" in html
    assert "xbook · Payroll &amp; Invoicing chat" in html  # eyebrow, & escaped
    # the worker's body is framed inside
    assert "BODY-MARKER" in html
    # the discreet attribution lives in the FOOTER, not the header/title
    assert "Generated by xbook · Payroll &amp; Invoicing chat · 2026-06-11" in html


def test_wrap_omits_status_strip_by_default_and_includes_it_when_given() -> None:
    base = dict(
        eyebrow="e",
        tenant="t",
        subtitle="s",
        worker="xbook",
        product="p",
        date="2026-06-12",
    )
    without = wrap("<p>x</p>", **base)
    assert "border-radius:50%" not in without  # no severity dot

    withit = wrap(
        "<p>x</p>",
        status={"severity": "red", "label": "1 needs you", "right": "chat summary"},
        **base,
    )
    assert "1 needs you" in withit
    assert "#dc2626" in withit  # red severity dot


def test_wrap_escapes_header_fields() -> None:
    html = wrap(
        "<p>x</p>",
        eyebrow="e",
        tenant="A & B Care <Ltd>",
        subtitle="s",
        worker="xbook",
        product="p",
        date="2026-06-12",
    )
    assert "A &amp; B Care &lt;Ltd&gt;" in html


def test_status_strip_headline_optional() -> None:
    with_headline = status_strip(
        severity="amber", label="3 need you", right="reconciliation", headline="Top item"
    )
    assert "Top item" in with_headline
    assert "#d97706" in with_headline  # amber

    without = status_strip(severity="green", label="all clear", right="x")
    assert "all clear" in without


def test_badge_and_section_eyebrow() -> None:
    assert "#059669" in badge("ok", "green")
    assert ">ok<" in badge("ok", "green")
    assert "What Milo did (0)" in section_eyebrow("What Milo did", 0)
    assert "(0)" in section_eyebrow("What Milo did", 0)
    assert "(" not in section_eyebrow("Suggested actions")  # count omitted
