"""The shared branded email shell — one definition of how a Clonway worker's email looks and how
it signs itself, so the brand and the worker-attribution breadcrumb can't drift across the fleet.

Stdlib-only string building (inline styles + table layout — the constraints every email client
forces): no Jinja, no images, <=640px. A worker renders its own body HTML and passes it to
:func:`wrap`, which frames it in the card, header band, optional status strip, and the footer
breadcrumb ``Generated by <worker> · <product> · <date>``.

The attribution breadcrumb is DISCREET by contract: it lives in the footer, never the header /
title / subject — the operator's prime real estate stays business content.
"""

from __future__ import annotations

from html import escape

# Design tokens (lifted from the xbook digest house style).
INK = "#1a1a1a"
MUTED = "#6b7280"
BORDER = "#e5e7eb"
PANEL = "#f9fafb"
LINK = "#1d4ed8"
BADGE_COLOURS = {"green": "#059669", "amber": "#d97706", "red": "#dc2626", "muted": "#6b7280"}


def breadcrumb(worker: str, product: str, date: str) -> str:
    """The worker-attribution line, as plain text (reused verbatim in the text/plain part):
    ``Generated by <worker> · <product> · <date>``."""
    return f"Generated by {worker} · {product} · {date}"


def badge(label: str, tone: str = "muted") -> str:
    """A small coloured pill (green / amber / red / muted)."""
    colour = BADGE_COLOURS.get(tone, BADGE_COLOURS["muted"])
    return (
        f'<span style="display:inline-block;padding:2px 8px;border-radius:10px;font-size:12px;'
        f'font-weight:600;color:#fff;background:{colour};">{escape(label)}</span>'
    )


def section_eyebrow(label: str, count: int | None = None) -> str:
    """An uppercase section label, e.g. ``WHAT MILO DID (0)`` (CSS uppercases; source keeps case)."""
    suffix = f" ({count})" if count is not None else ""
    return (
        f'<div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;'
        f'color:{MUTED};font-weight:700;margin:20px 0 8px;">{escape(label)}{suffix}</div>'
    )


def status_strip(*, severity: str, label: str, right: str = "", headline: str = "") -> str:
    """A pulse-style status band: severity dot + uppercase label + right-label, optional headline.

    ``severity`` is one of ``green`` / ``amber`` / ``red`` (anything else falls back to green).
    """
    colour = BADGE_COLOURS.get(severity, BADGE_COLOURS["green"])
    headline_html = (
        f'<div style="font-size:18px;line-height:1.3;font-weight:700;margin-top:8px;'
        f'letter-spacing:-0.01em;color:{INK};">{escape(headline)}</div>'
        if headline
        else ""
    )
    return (
        '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" '
        f'style="border-collapse:collapse;background:#ffffff;border:1px solid {BORDER};'
        'border-radius:8px;">'
        '<tr><td style="padding:16px 18px;">'
        '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" '
        'style="border-collapse:collapse;"><tr>'
        '<td style="vertical-align:middle;width:14px;padding-right:8px;">'
        f'<div style="width:12px;height:12px;border-radius:50%;background:{colour};"></div></td>'
        '<td style="vertical-align:middle;font-size:11px;letter-spacing:0.06em;'
        f'text-transform:uppercase;font-weight:700;color:{colour};">{escape(label)}</td>'
        '<td style="vertical-align:middle;text-align:right;font-size:12px;'
        f'color:{MUTED};">{escape(right)}</td>'
        f"</tr></table>{headline_html}</td></tr></table>"
    )


def wrap(
    body_html: str,
    *,
    eyebrow: str,
    tenant: str,
    subtitle: str,
    worker: str,
    product: str,
    date: str,
    status: dict[str, str] | None = None,
) -> str:
    """Frame a worker's ``body_html`` in the branded card and return a full HTML document.

    Header band: ``eyebrow`` (small mono uppercase) -> ``tenant`` -> ``subtitle``. Optional
    ``status`` strip (a mapping accepted by :func:`status_strip`). Footer: the discreet
    ``Generated by <worker> · <product> · <date>`` breadcrumb.
    """
    status_row = (
        f'<tr><td style="padding:16px 24px 0;">{status_strip(**status)}</td></tr>' if status else ""
    )
    crumb = escape(breadcrumb(worker, product, date))
    return (
        '<!DOCTYPE html>\n<html lang="en">\n<head>'
        '<meta charset="utf-8" />'
        '<meta name="viewport" content="width=device-width,initial-scale=1" />'
        f"<title>{escape(eyebrow)} &mdash; {escape(date)}</title></head>\n"
        f'<body style="margin:0;padding:0;background:#f3f4f6;'
        "font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;"
        f'color:{INK};">'
        '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" '
        'style="background:#f3f4f6;padding:24px 0;"><tr><td align="center">'
        '<table role="presentation" width="640" cellpadding="0" cellspacing="0" '
        f'style="background:#ffffff;max-width:640px;border:1px solid {BORDER};border-radius:8px;">'
        # Header band
        f'<tr><td style="padding:20px 24px;border-bottom:1px solid {BORDER};">'
        '<div style="font-size:12px;letter-spacing:0.08em;text-transform:uppercase;'
        f'color:{MUTED};font-family:ui-monospace,SFMono-Regular,Menlo,monospace;">'
        f"{escape(eyebrow)}</div>"
        f'<div style="font-size:22px;font-weight:700;margin-top:2px;">{escape(tenant)}</div>'
        f'<div style="font-size:14px;color:{MUTED};margin-top:2px;">{escape(subtitle)}</div>'
        "</td></tr>"
        f"{status_row}"
        # Body
        f'<tr><td style="padding:4px 24px 8px;">{body_html}</td></tr>'
        # Footer breadcrumb
        f'<tr><td style="padding:14px 24px;background:{PANEL};border-top:1px solid {BORDER};'
        f'font-size:12px;color:{MUTED};">{crumb}</td></tr>'
        "</table></td></tr></table></body></html>"
    )
